### ISSUE TITLE
Win7上运行报错

### ISSUE THREAD

**Issue by kbj** [wxsms/daily-signer#2]
```
C:\daily-signer (master -> origin) (daily-sign@0.0.1)
λ npm install
npm WARN daily-sign@0.0.1 No repository field.

up to date in 0.39s

C:\daily-signer (master -> origin) (daily-sign@0.0.1)
λ npm start

> daily-sign@0.0.1 start C:\daily-signer
> node index.js

module.js:674
    throw err;
    ^

SyntaxError: C:\daily-signer\config\user.json: Unexpected token ， in JSON at
position 110
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:671:27)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\daily-signer\src\modules\jd\index.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! daily-sign@0.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the daily-sign@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-10-24T14_15_03_314Z-debug.log
```
node版本：

```
λ node -v
v8.11.4
```

**Comment by kbj** [comment]
JSON错误。 已解决
